create type "public"."profile_type" as enum ('admin', 'clerk_logistics', 'clerk_transport', 'support', 'tracker', 'finance', 'super_admin');

create table "public"."article_tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "article_id" bigint,
    "tag_id" bigint
);


alter table "public"."article_tags" enable row level security;

create table "public"."articles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text,
    "content" text,
    "category_id" bigint,
    "published_at" timestamp without time zone,
    "updated_at" timestamp with time zone,
    "deleted_at" timestamp with time zone
);


alter table "public"."articles" enable row level security;

create table "public"."categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "description" text,
    "updated_at" timestamp with time zone,
    "deleted_at" timestamp with time zone
);


alter table "public"."categories" enable row level security;

create table "public"."tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "updated_at" timestamp with time zone,
    "deleted_at" timestamp with time zone
);


alter table "public"."tags" enable row level security;

CREATE UNIQUE INDEX aritcle_tags_pkey ON public.article_tags USING btree (id);

CREATE UNIQUE INDEX articles_pkey ON public.articles USING btree (id);

CREATE UNIQUE INDEX categories_name_key ON public.categories USING btree (name);

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);

CREATE UNIQUE INDEX tags_pkey ON public.tags USING btree (id);

alter table "public"."article_tags" add constraint "aritcle_tags_pkey" PRIMARY KEY using index "aritcle_tags_pkey";

alter table "public"."articles" add constraint "articles_pkey" PRIMARY KEY using index "articles_pkey";

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "public"."article_tags" add constraint "aritcle_tags_article_id_fkey" FOREIGN KEY (article_id) REFERENCES articles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."article_tags" validate constraint "aritcle_tags_article_id_fkey";

alter table "public"."article_tags" add constraint "aritcle_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES tags(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."article_tags" validate constraint "aritcle_tags_tag_id_fkey";

alter table "public"."articles" add constraint "articles_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."articles" validate constraint "articles_category_id_fkey";

alter table "public"."categories" add constraint "categories_name_key" UNIQUE using index "categories_name_key";

grant delete on table "public"."article_tags" to "anon";

grant insert on table "public"."article_tags" to "anon";

grant references on table "public"."article_tags" to "anon";

grant select on table "public"."article_tags" to "anon";

grant trigger on table "public"."article_tags" to "anon";

grant truncate on table "public"."article_tags" to "anon";

grant update on table "public"."article_tags" to "anon";

grant delete on table "public"."article_tags" to "authenticated";

grant insert on table "public"."article_tags" to "authenticated";

grant references on table "public"."article_tags" to "authenticated";

grant select on table "public"."article_tags" to "authenticated";

grant trigger on table "public"."article_tags" to "authenticated";

grant truncate on table "public"."article_tags" to "authenticated";

grant update on table "public"."article_tags" to "authenticated";

grant delete on table "public"."article_tags" to "service_role";

grant insert on table "public"."article_tags" to "service_role";

grant references on table "public"."article_tags" to "service_role";

grant select on table "public"."article_tags" to "service_role";

grant trigger on table "public"."article_tags" to "service_role";

grant truncate on table "public"."article_tags" to "service_role";

grant update on table "public"."article_tags" to "service_role";

grant delete on table "public"."articles" to "anon";

grant insert on table "public"."articles" to "anon";

grant references on table "public"."articles" to "anon";

grant select on table "public"."articles" to "anon";

grant trigger on table "public"."articles" to "anon";

grant truncate on table "public"."articles" to "anon";

grant update on table "public"."articles" to "anon";

grant delete on table "public"."articles" to "authenticated";

grant insert on table "public"."articles" to "authenticated";

grant references on table "public"."articles" to "authenticated";

grant select on table "public"."articles" to "authenticated";

grant trigger on table "public"."articles" to "authenticated";

grant truncate on table "public"."articles" to "authenticated";

grant update on table "public"."articles" to "authenticated";

grant delete on table "public"."articles" to "service_role";

grant insert on table "public"."articles" to "service_role";

grant references on table "public"."articles" to "service_role";

grant select on table "public"."articles" to "service_role";

grant trigger on table "public"."articles" to "service_role";

grant truncate on table "public"."articles" to "service_role";

grant update on table "public"."articles" to "service_role";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."tags" to "anon";

grant insert on table "public"."tags" to "anon";

grant references on table "public"."tags" to "anon";

grant select on table "public"."tags" to "anon";

grant trigger on table "public"."tags" to "anon";

grant truncate on table "public"."tags" to "anon";

grant update on table "public"."tags" to "anon";

grant delete on table "public"."tags" to "authenticated";

grant insert on table "public"."tags" to "authenticated";

grant references on table "public"."tags" to "authenticated";

grant select on table "public"."tags" to "authenticated";

grant trigger on table "public"."tags" to "authenticated";

grant truncate on table "public"."tags" to "authenticated";

grant update on table "public"."tags" to "authenticated";

grant delete on table "public"."tags" to "service_role";

grant insert on table "public"."tags" to "service_role";

grant references on table "public"."tags" to "service_role";

grant select on table "public"."tags" to "service_role";

grant trigger on table "public"."tags" to "service_role";

grant truncate on table "public"."tags" to "service_role";

grant update on table "public"."tags" to "service_role";

create policy "Users can create artcle_tags"
on "public"."article_tags"
as permissive
for all
to public
using (true);


create policy "Policy with security definerUsers can create articles functions"
on "public"."articles"
as permissive
for all
to public
using (true);


create policy "Users can create categories"
on "public"."categories"
as permissive
for all
to public
using (true);


create policy "Users can create tags"
on "public"."tags"
as permissive
for all
to public
using (true);



